In [65]:
import numpy as np 
import pandas as pd

In [66]:
df = pd.read_csv('/content/new_quotes - new_quotes.csv')
df

,Unnamed: 0,Unnamed: 0.1,quote,author,category
0,0,0.0,“The coming era of Artificial Intelligence wil...,– Amit Ray,AI
1,1,1.0,“Artificial intelligence would be the ultimate...,– Larry Page,AI
2,2,2.0,"“Cyber hygiene, patching vulnerabilities, secu...",– James Scott,AI
3,3,3.0,“You have to talk about ‘The Terminator’ if yo...,– Gray Scott,AI
4,4,4.0,“I believe that at the end of the century the ...,– Alan Turing,AI
...,...,...,...,...,...
154,23,NaN,“Is artificial intelligence less than our inte...,—Spike Jonze,Machine Learning
155,24,NaN,"“By far, the greatest danger of Artificial Int...",—Eliezer Yudkowsky,Machine Learning
156,25,NaN,“The sad thing about artificial intelligence i...,—Jean Baudrillard,Machine Learning
157,26,NaN,“Forget artificial intelligence – in the brave...,—Tom Chatfield,Machine Learning
158,27,NaN,“Before we work on artificial intelligence why...,—Steve Polyak,Machine Learning

In [67]:
df.rename(columns = {'Unnamed: 0':'ID'}, inplace = True)

In [68]:
import re
def preprocess(text):
    text = re.sub(r'[^\w\s\']',' ', text)
    return text.strip().lower()

In [69]:
df['quote'] = df['quote'].map(preprocess)
df['author']=df['author'].map(preprocess)

In [70]:
df

,ID,Unnamed: 0.1,quote,author,category
0,0,0.0,the coming era of artificial intelligence will...,amit ray,AI
1,1,1.0,artificial intelligence would be the ultimate ...,larry page,AI
2,2,2.0,cyber hygiene patching vulnerabilities secur...,james scott,AI
3,3,3.0,you have to talk about the terminator if you...,gray scott,AI
4,4,4.0,i believe that at the end of the century the u...,alan turing,AI
...,...,...,...,...,...
154,23,NaN,is artificial intelligence less than our intel...,spike jonze,Machine Learning
155,24,NaN,by far the greatest danger of artificial inte...,eliezer yudkowsky,Machine Learning
156,25,NaN,the sad thing about artificial intelligence is...,jean baudrillard,Machine Learning
157,26,NaN,forget artificial intelligence in the brave ...,tom chatfield,Machine Learning
158,27,NaN,before we work on artificial intelligence why ...,steve polyak,Machine Learning

In [71]:
df['author']=df['author'].str.replace(' ', '')

In [72]:
df

,ID,Unnamed: 0.1,quote,author,category
0,0,0.0,the coming era of artificial intelligence will...,amitray,AI
1,1,1.0,artificial intelligence would be the ultimate ...,larrypage,AI
2,2,2.0,cyber hygiene patching vulnerabilities secur...,jamesscott,AI
3,3,3.0,you have to talk about the terminator if you...,grayscott,AI
4,4,4.0,i believe that at the end of the century the u...,alanturing,AI
...,...,...,...,...,...
154,23,NaN,is artificial intelligence less than our intel...,spikejonze,Machine Learning
155,24,NaN,by far the greatest danger of artificial inte...,eliezeryudkowsky,Machine Learning
156,25,NaN,the sad thing about artificial intelligence is...,jeanbaudrillard,Machine Learning
157,26,NaN,forget artificial intelligence in the brave ...,tomchatfield,Machine Learning
158,27,NaN,before we work on artificial intelligence why ...,stevepolyak,Machine Learning

In [73]:
df['tags']=df['quote']+' '+df['author']+' '+df['category']

In [74]:
df['tags'].iloc[0]

'the coming era of artificial intelligence will not be the era of war  but be the era of deep compassion  non violence  and love amitray AI'

In [75]:
new_df=df.drop(columns=['author','category'])

In [76]:
new_df

,ID,Unnamed: 0.1,quote,tags
0,0,0.0,the coming era of artificial intelligence will...,the coming era of artificial intelligence will...
1,1,1.0,artificial intelligence would be the ultimate ...,artificial intelligence would be the ultimate ...
2,2,2.0,cyber hygiene patching vulnerabilities secur...,cyber hygiene patching vulnerabilities secur...
3,3,3.0,you have to talk about the terminator if you...,you have to talk about the terminator if you...
4,4,4.0,i believe that at the end of the century the u...,i believe that at the end of the century the u...
...,...,...,...,...
154,23,NaN,is artificial intelligence less than our intel...,is artificial intelligence less than our intel...
155,24,NaN,by far the greatest danger of artificial inte...,by far the greatest danger of artificial inte...
156,25,NaN,the sad thing about artificial intelligence is...,the sad thing about artificial intelligence is...
157,26,NaN,forget artificial intelligence in the brave ...,forget artificial intelligence in the brave ...
158,27,NaN,before we work on artificial intelligence why ...,before we work on artificial intelligence why ...

In [77]:
# from sklearn.feature_extraction.text import CountVectorizer
# cv = CountVectorizer(max_features=5000)

In [78]:
# vector = cv.fit_transform(new_df['tags']).toarray()

In [79]:
!pip install nltk

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: nltk in /usr/local/lib/python3.8/dist-packages (3.7)
Requirement already satisfied: click in /usr/local/lib/python3.8/dist-packages (from nltk) (7.1.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.8/dist-packages (from nltk) (4.64.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.8/dist-packages (from nltk) (1.2.0)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.8/dist-packages (from nltk) (2022.6.2)

In [80]:
import nltk
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
nltk.download('omw-1.4')
lemmatizer = WordNetLemmatizer()
l1=[]
for word in new_df['tags']:
  l1.append(WordNetLemmatizer().lemmatize(word,'v'))

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

In [81]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
vector = vectorizer.fit_transform(l1)

In [82]:
vector.shape

(159, 1632)

In [83]:
from sklearn.metrics.pairwise import cosine_similarity

In [84]:
similarity = cosine_similarity(vector)

In [85]:
similarity

array([[1.        , 0.07576961, 0.03643723, ..., 0.06265348, 0.09485765,
        0.02727291],
       [0.07576961, 1.        , 0.03033434, ..., 0.12454611, 0.09995101,
        0.15375617],
       [0.03643723, 0.03033434, 1.        , ..., 0.07858391, 0.08168505,
        0.05594823],
       ...,
       [0.06265348, 0.12454611, 0.07858391, ..., 1.        , 0.15023573,
        0.16029586],
       [0.09485765, 0.09995101, 0.08168505, ..., 0.15023573, 1.        ,
        0.15909103],
       [0.02727291, 0.15375617, 0.05594823, ..., 0.16029586, 0.15909103,
        1.        ]])

In [86]:
def recommend(quote):
    l1=[]
    index = new_df[new_df['quote'] == quote].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:6]:
        l1.append(new_df.iloc[i[0]].quote)
    return l1

In [87]:
new_df['quote'].iloc[0]

'the coming era of artificial intelligence will not be the era of war  but be the era of deep compassion  non violence  and love'

In [88]:
l1=recommend('the coming era of artificial intelligence will not be the era of war  but be the era of deep compassion  non violence  and love')

In [89]:
for i in range(len(l1)):
    print(i+1,". ",l1[i])

1 .  we should expect a  big data 2 0  phase to follow  big data 1 0   once firms have become capable of processing massive data in a flexible fashion  they should begin asking   what can i do that i couldn t do before  or do better than i could do before   this is likely to be the golden era of data science
2 .  i believe that at the end of the century the use of words and general educated opinion will have altered so much that one will be able to speak of machines thinking without expecting to be contradicted
3 .  the real question is  when will we draft an artificial intelligence bill of rights  what will that consist of  and who will get to decide that
4 .  a big theme that i keep coming back to is  where is the love  it s basically just finding out which users are passionate about the product  what is the use case on the product that those people have  why do they actually love the product  and that gives you a good core of information to guide every part of your business  so messaging  you want to reflect that  but also  now that you know that  you want to make sure that you can really get a lot more people to that particular type of use case and that particular type of gratifying experience  so understanding user gratification is really critical in all of it
5 .  it s going to be interesting to see how society deals with artificial intelligence  but it will definitely be cool